ALTER TABLE contact ADD COLUMN IF NOT EXISTS created_locally BOOLEAN DEFAULT FALSE;
ALTER TABLE contact ADD COLUMN IF NOT EXISTS parent_id INTEGER;
ALTER TABLE contact ADD COLUMN IF NOT EXISTS title_override VARCHAR (128);
ALTER TABLE contact ADD COLUMN IF NOT EXISTS uploaded_image_url VARCHAR (255);
ALTER TABLE contact ADD COLUMN IF NOT EXISTS color_code VARCHAR (31);
