ALTER TABLE contact ADD COLUMN IF NOT EXISTS created_locally BOOLEAN DEFAULT FALSE;
ALTER TABLE contact ADD COLUMN IF NOT EXISTS parent_id VARCHAR (18);
ALTER TABLE contact ADD COLUMN IF NOT EXISTS title_override VARCHAR (128);
ALTER TABLE contact ADD COLUMN IF NOT EXISTS uploaded_image_url VARCHAR (255);
